import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";
import { SiteHeader } from "~/components/SiteHeader";
import { api } from "~/utils/api";

type Provider = "dali" | "free" | "sino";

const PROVIDER_LABELS: Record<Provider, string> = {
  dali: "Dalivali",
  free: "Freemeteo",
  sino: "Sinoptik",
};

function isProvider(value: unknown): value is Provider {
  return value === "dali" || value === "free" || value === "sino";
}

const Detailed: NextPage = () => {
  const router = useRouter();
  const cityId =
    typeof router.query.cityId === "string" ? Number(router.query.cityId) : undefined;
  const date =
    typeof router.query.date === "string" ? new Date(router.query.date) : undefined;

  const [provider, setProvider] = useState<Provider>(
    isProvider(router.query.provider) ? router.query.provider : "dali",
  );

  const { data: daliRows } = api.providers.getCertainDateDali.useQuery({ cityId, date });
  const { data: freeRows } = api.providers.getCertainDateFree.useQuery({ cityId, date });
  const { data: sinoRows } = api.providers.getCertainDateSino.useQuery({ cityId, date });

  return (
    <>
      <Head>
        <title>MergeMeteo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader showTagline={false}>
        {(Object.keys(PROVIDER_LABELS) as Provider[])
          .filter((p) => p !== provider)
          .map((p) => (
            <button
              key={p}
              onClick={() => setProvider(p)}
              className="border-slate-400 flex rounded-xl border-2 bg-thirdLayer p-3"
            >
              Switch to {PROVIDER_LABELS[p]}
            </button>
          ))}
        <Link
          className="border-slate-400 flex rounded-xl border-2 bg-thirdLayer p-3"
          href="/"
        >
          Last Week
        </Link>
        <Link
          className="border-slate-400 flex rounded-xl border-2 bg-thirdLayer p-3"
          href="/forecast"
        >
          Forecast
        </Link>
      </SiteHeader>
      <div className="flex justify-center p-4">
        <div className="mt-4 flex justify-self-center rounded-lg border-2 border-solid border-gray-400 bg-secondLayer p-4">
          <p className="justify-center font-mono text-lg font-medium text-white">
            Current provider: {PROVIDER_LABELS[provider]}
          </p>
        </div>
      </div>
      <main className="flex justify-center p-4">
        <div className="flex w-2/3 flex-col rounded-lg border-2 border-solid border-gray-400 bg-firstLayer">
          <table className="m-4 table-auto rounded-lg border-2 bg-secondLayer text-center">
            <thead>
              <tr>
                <th>From date</th>
                <th>Hour</th>
                <th>Max Temp</th>
                <th>Min Temp</th>
                {provider !== "free" && <th>Wind Spd</th>}
                <th>Wind Dir</th>
                {provider === "dali" && <th>Humidity</th>}
                <th>Text</th>
                <th>Img</th>
              </tr>
            </thead>
            <tbody className="rounded-lg p-2">
              {provider === "dali" &&
                daliRows?.map((row) => (
                  <tr
                    key={row.id}
                    className="m-2 rounded-lg border-2 border-gray-600 bg-thirdLayer"
                  >
                    <td className="p-2">{row.createdAt.toDateString()}</td>
                    <td>{row.createdAt.getHours()}</td>
                    <td>{row.tmax}</td>
                    <td>{row.tmin}</td>
                    <td>{row.wspd}</td>
                    <td>{row.wdir}</td>
                    <td>{row.humidity}</td>
                    <td>{row.text}</td>
                    <td>
                      {row.image && (
                        <img
                          src={`data:image/jpeg;base64,${row.image.src}`}
                          alt="forecast icon"
                          className="mix-blend-multiply"
                        />
                      )}
                    </td>
                  </tr>
                ))}
              {provider === "free" &&
                freeRows?.map((row) => (
                  <tr
                    key={row.id}
                    className="m-2 rounded-lg border-2 border-gray-600 bg-thirdLayer"
                  >
                    <td className="p-2">{row.createdAt.toDateString()}</td>
                    <td>{row.createdAt.getHours()}</td>
                    <td>{row.tmax}</td>
                    <td>{row.tmin}</td>
                    <td>{row.wdir}</td>
                    <td>{row.text}</td>
                    <td>
                      {row.image && (
                        <img
                          src={`data:image/jpeg;base64,${row.image.src}`}
                          alt="forecast icon"
                          className="mix-blend-multiply"
                        />
                      )}
                    </td>
                  </tr>
                ))}
              {provider === "sino" &&
                sinoRows?.map((row) => (
                  <tr
                    key={row.id}
                    className="m-2 rounded-lg border-2 border-gray-600 bg-thirdLayer"
                  >
                    <td className="p-2">{row.createdAt.toDateString()}</td>
                    <td>{row.createdAt.getHours()}</td>
                    <td>{row.tmax}</td>
                    <td>{row.tmin}</td>
                    <td>{row.wspd}</td>
                    <td>{row.wdir}</td>
                    <td>{row.text}</td>
                    <td>
                      {row.image && (
                        <img
                          src={`data:image/jpeg;base64,${row.image.src}`}
                          alt="forecast icon"
                          className="mix-blend-multiply"
                        />
                      )}
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
};

export default Detailed;
