import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { CitySelector } from "~/components/CitySelector";
import { ForecastCard } from "~/components/ForecastCard";
import { TemperatureChart } from "~/components/ForecastChart";
import { ProviderSection } from "~/components/ProviderSection";
import { SiteHeader } from "~/components/SiteHeader";
import { aggregateDailyAverages } from "~/utils/aggregate";
import { api } from "~/utils/api";

const Forecast: NextPage = () => {
  const { data: cities } = api.cities.getAll.useQuery();
  const [cityId, setCityId] = useState<number>();

  const { data: dali } = api.providers.getForNextWeekDali.useQuery({ cityId });
  const { data: free } = api.providers.getForNextWeekFree.useQuery({ cityId });
  const { data: sino } = api.providers.getForNextWeekSino.useQuery({ cityId });

  const daliByDate = aggregateDailyAverages(dali, (row) => row.forecastDay);
  const freeByDate = aggregateDailyAverages(free, (row) => row.forecastDay);
  const sinoByDate = aggregateDailyAverages(sino, (row) => row.forecastDate);

  return (
    <>
      <Head>
        <title>MergeMeteo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader>
        <Link
          className="border-slate-400 flex rounded-xl border-2 bg-thirdLayer p-3"
          href="/"
        >
          Last Week
        </Link>
      </SiteHeader>
      <main className="flex justify-center p-4">
        <CitySelector cities={cities} onSelect={setCityId} />
        <div className="border-slate-600 m-4 flex flex-grow flex-col rounded-lg border-2 border-solid bg-secondLayer p-4">
          {!cityId && (
            <div className="flex flex-col justify-center rounded-lg border-2 border-solid bg-thirdLayer p-4">
              <p className="font-mono flex justify-center text-xl font-semibold">
                Please select a city
              </p>
              <div className="m-4 flex justify-center rounded-lg border-2 border-solid bg-gray-400 p-4">
                <p>
                  After selecting a city, you will be presented with
                  information about the{" "}
                  <span className="underline">next week</span> from three
                  different weather forecast sources.
                </p>
              </div>
            </div>
          )}
          {cityId && (
            <div className="border-slate-400 m-4 flex max-h-fit flex-grow flex-col rounded-lg border-2 border-solid bg-secondLayer">
              <ProviderSection
                title="From DaliVali for next week"
                chart={<TemperatureChart data={daliByDate} />}
              >
                {Object.keys(daliByDate)
                  .sort()
                  .map((date) => {
                    const avg = daliByDate[date]!;
                    return (
                      <ForecastCard
                        key={date}
                        datePrefix="For"
                        date={date}
                        avgTmax={avg.avgTmax}
                        avgTmin={avg.avgTmin}
                        avgHumidity={avg.avgHumidity}
                        detailsHref={{
                          pathname: "/detailed",
                          query: { date, cityId, provider: "dali" },
                        }}
                      />
                    );
                  })}
              </ProviderSection>

              <ProviderSection
                title="From Sinoptik for next week"
                chart={<TemperatureChart data={sinoByDate} />}
              >
                {Object.keys(sinoByDate)
                  .sort()
                  .map((date) => {
                    const avg = sinoByDate[date]!;
                    return (
                      <ForecastCard
                        key={date}
                        datePrefix="For"
                        date={date}
                        avgTmax={avg.avgTmax}
                        avgTmin={avg.avgTmin}
                        detailsHref={{
                          pathname: "/detailed",
                          query: { date, cityId, provider: "sino" },
                        }}
                      />
                    );
                  })}
              </ProviderSection>

              <ProviderSection
                title="From Freemeteo for next week"
                chart={<TemperatureChart data={freeByDate} />}
              >
                {Object.keys(freeByDate)
                  .sort()
                  .map((date) => {
                    const avg = freeByDate[date]!;
                    return (
                      <ForecastCard
                        key={date}
                        datePrefix="For"
                        date={date}
                        avgTmax={avg.avgTmax}
                        avgTmin={avg.avgTmin}
                        detailsHref={{
                          pathname: "/detailed",
                          query: { date, cityId, provider: "free" },
                        }}
                      />
                    );
                  })}
              </ProviderSection>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Forecast;
