import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { CitySelector } from "~/components/CitySelector";
import { ForecastCard } from "~/components/ForecastCard";
import { MaeChart, TemperatureChart } from "~/components/ForecastChart";
import { ProviderSection } from "~/components/ProviderSection";
import { SiteHeader } from "~/components/SiteHeader";
import { aggregateDailyAverages } from "~/utils/aggregate";
import { api } from "~/utils/api";
import { averageMae, computeMaeByDate } from "~/utils/mae";

const Home: NextPage = () => {
  const { data: cities } = api.cities.getAll.useQuery();
  const [cityId, setCityId] = useState<number>();

  const { data: dali } = api.providers.getForTodayDaysDali.useQuery({ cityId });
  const { data: free } = api.providers.getForTodayDaysFree.useQuery({ cityId });
  const { data: sino } = api.providers.getForTodayDaysSino.useQuery({ cityId });

  const daliByDate = aggregateDailyAverages(dali, (row) => row.createdAt);
  const freeByDate = aggregateDailyAverages(free, (row) => row.createdAt);
  const sinoByDate = aggregateDailyAverages(sino, (row) => row.createdAt);

  const daliMae = computeMaeByDate(dali, (row) => row.createdAt);
  const freeMae = computeMaeByDate(free, (row) => row.createdAt);
  const sinoMae = computeMaeByDate(sino, (row) => row.createdAt);

  const daliAvgMae = averageMae(daliMae);
  const freeAvgMae = averageMae(freeMae);
  const sinoAvgMae = averageMae(sinoMae);

  return (
    <>
      <Head>
        <title>MergeMeteo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader>
        <Link
          className="border-slate-400 flex rounded-xl border-2 bg-thirdLayer p-3"
          href="/forecast"
        >
          Forecast
        </Link>
      </SiteHeader>
      <main className="flex justify-center p-4">
        <CitySelector cities={cities} onSelect={setCityId} />
        <div className="border-slate-600 m-4 flex flex-grow flex-col rounded-lg border-2 border-solid bg-secondLayer p-4">
          {!cityId && (
            <div className="flex flex-col justify-center rounded-lg border-2 border-solid bg-thirdLayer p-4">
              <p className="font-mono flex justify-center text-xl font-semibold">
                Please select a city
              </p>
              <div className="m-4 flex justify-center rounded-lg border-2 border-solid bg-gray-400 p-4">
                <p>
                  After selecting a city, you will be presented with
                  information about the{" "}
                  <span className="underline">past week</span> from three
                  different weather forecast sources.
                </p>
              </div>
            </div>
          )}
          {cityId && (
            <div className="border-slate-400 m-4 flex max-h-fit flex-grow flex-col rounded-lg border-2 border-solid bg-secondLayer">
              <div className="border-slate-400 m-4 flex max-h-fit flex-grow flex-col rounded-lg border-2 border-solid bg-thirdLayer p-4">
                <div className="flex flex-row justify-center">
                  <div className="flex flex-col gap-2 p-4">
                    <p className="font-mono text-md font-semibold">
                      The average MAE for Tmax from the different providers
                      for today is:
                    </p>
                    <p>Dalivali: {daliAvgMae.avgMaeTmax.toFixed(2)} </p>
                    <p>Freemeteo: {freeAvgMae.avgMaeTmax.toFixed(2)} </p>
                    <p>Sinoptik: {sinoAvgMae.avgMaeTmax.toFixed(2)} </p>
                  </div>
                  <div className="flex flex-col gap-2 p-4">
                    <p className="font-mono text-md font-semibold">
                      The average MAE for Tmin from the different providers
                      for today is:
                    </p>
                    <p>Dalivali: {daliAvgMae.avgMaeTmin.toFixed(2)} </p>
                    <p>Freemeteo: {freeAvgMae.avgMaeTmin.toFixed(2)} </p>
                    <p>Sinoptik: {sinoAvgMae.avgMaeTmin.toFixed(2)} </p>
                  </div>
                </div>
              </div>

              <ProviderSection
                title="From Dalivali for Today"
                chart={
                  <>
                    <TemperatureChart data={daliByDate} />
                    <MaeChart data={daliMae} />
                  </>
                }
              >
                {Object.keys(daliByDate)
                  .sort()
                  .map((date) => {
                    const avg = daliByDate[date]!;
                    return (
                      <ForecastCard
                        key={date}
                        date={date}
                        avgTmax={avg.avgTmax}
                        avgTmin={avg.avgTmin}
                        avgHumidity={avg.avgHumidity}
                        detailsHref={{
                          pathname: "/detailed",
                          query: { date, cityId, provider: "dali" },
                        }}
                      />
                    );
                  })}
              </ProviderSection>

              <ProviderSection
                title="From Sinoptik for Today"
                chart={
                  <>
                    <TemperatureChart data={sinoByDate} />
                    <MaeChart data={sinoMae} />
                  </>
                }
              >
                {Object.keys(sinoByDate)
                  .sort()
                  .map((date) => {
                    const avg = sinoByDate[date]!;
                    return (
                      <ForecastCard
                        key={date}
                        date={date}
                        avgTmax={avg.avgTmax}
                        avgTmin={avg.avgTmin}
                        detailsHref={{
                          pathname: "/detailed",
                          query: { date, cityId, provider: "sino" },
                        }}
                      />
                    );
                  })}
              </ProviderSection>

              <ProviderSection
                title="From Freemeteo for Today"
                chart={
                  <>
                    <TemperatureChart data={freeByDate} />
                    <MaeChart data={freeMae} />
                  </>
                }
              >
                {Object.keys(freeByDate)
                  .sort()
                  .map((date) => {
                    const avg = freeByDate[date]!;
                    return (
                      <ForecastCard
                        key={date}
                        date={date}
                        avgTmax={avg.avgTmax}
                        avgTmin={avg.avgTmin}
                        detailsHref={{
                          pathname: "/detailed",
                          query: { date, cityId, provider: "free" },
                        }}
                      />
                    );
                  })}
              </ProviderSection>
            </div>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
